# Python basics for Brett

Welcome. This notebook is a hands-on tour of Python and object-oriented programming, plus a look at how Python talks to Wolfram Language.

**How to use it**

1. Select the kernel **`.venv`** (the virtual environment in this folder) if Cursor / Jupyter asks.
2. Click a cell, then press **Shift+Enter** to run it.
3. Run the cells in order from top to bottom.

A *cell* is one block of text or code. Markdown cells are notes. Code cells are Python you can execute.

## 1. Run simple, raw Python

A notebook is a Python interpreter with notes in between. The next cells are ordinary Python — no files, no libraries, no classes yet.

In [1]:
print("Hello, Brett.")
print(2 + 2)
print(3 * 7)
print(2 ** 8)  # ** means exponent: 2 to the 8th power

Hello, Brett.
4
21
256

**Variables** store values under a name. Python figures out the type for you.

In [2]:
name = "Brett"
games = 10
points = 187
ppg = points / games

print(name)
print(type(name), type(games), type(ppg))
print(f"{name} averaged {ppg:.1f} points per game.")

Brett
<class 'str'> <class 'int'> <class 'float'>
Brett averaged 18.7 points per game.

**Lists** hold an ordered collection. **`for`** loops walk through them. **`if`** chooses a branch.

In [3]:
scores = [22, 31, 18, 27, 14]

total = 0
for score in scores:
    total = total + score

average = total / len(scores)
print("scores:", scores)
print("average:", average)

if average >= 20:
    print("Hot streak.")
else:
    print("Cold night.")

scores: [22, 31, 18, 27, 14]
average: 22.4
Hot streak.

A **function** packages a piece of logic you can reuse. `def` defines it; calling `double(5)` runs it.

In [4]:
def double(x):
    return x * 2

def greeting(person):
    return f"Welcome to Python, {person}."

print(double(5))
print(greeting("Brett"))

10
Welcome to Python, Brett.

## 2. Load a class from a `.py` file

Object-oriented programming (OOP) groups *data* and *behavior* together.

- A **class** is the blueprint (`Player` in `player.py`).
- An **instance** (or object) is one concrete thing built from that blueprint (`lebron`, `jokic`).
- A **property** (attribute) is data stored on the instance: `lebron.team`.
- A **method** is a function that belongs to the class: `lebron.points_per_game()`.

Open `player.py` in the editor and read it, then run the cells below.

### 2a. Instantiate the class

`from player import Player` loads the class defined in `player.py` in this folder. Calling `Player(...)` **instantiates** it — it runs `__init__` and returns a new object.

In [5]:
from player import Player

lebron = Player("LeBron James", "Lakers", 1766, 71)
jokic = Player("Nikola Jokic", "Nuggets", 2094, 79)

print(lebron)
print(type(lebron))
print(jokic)

<player.Player object at 0x1088fa900>
<class 'player.Player'>
<player.Player object at 0x10893c190>

### 2b. Access a property

Dot notation reads data stored on the instance. `lebron.name` and `lebron.team` are properties set in `__init__`.

In [6]:
print(lebron.name)
print(lebron.team)
print(lebron.points)
print(lebron.games)

# You can also assign a new value to a property.
lebron.team = "Lakers"
print("team is still:", lebron.team)

LeBron James
Lakers
1766
71
team is still: Lakers

### 2c. Access a method

A method is called with parentheses. `self` inside the class is the instance you called it on, so `lebron.points_per_game()` uses LeBron's points and games.

In [7]:
print(lebron.points_per_game())
print(jokic.points_per_game())
print(lebron.summary())
print(jokic.summary())

24.87323943661972
26.50632911392405
LeBron James (Lakers) scored 1766 points in 71 games (24.9 PPG).
Nikola Jokic (Nuggets) scored 2094 points in 79 games (26.5 PPG).

## 3. Common libraries: `os`, `numpy`, `pandas`

A **library** (or package) is code someone else wrote that you import. Three you will see constantly:

| Library | What it is for |
| --- | --- |
| `os` | Talk to the operating system: paths, folders, environment |
| `numpy` | Fast numeric arrays and math |
| `pandas` | Tables (spreadsheets) of data |

If an import fails, install into this repo's virtual environment:

```bash
.venv/bin/pip install pandas numpy
```

### `os` — files and folders

In [8]:
import os

print("current folder:", os.getcwd())
print("files in this folder:")
for name in sorted(os.listdir(".")):
    if not name.startswith("."):
        print(" ", name)

player_path = os.path.join(os.getcwd(), "player.py")
print("player.py exists:", os.path.exists(player_path))
print("player.py size (bytes):", os.path.getsize(player_path))

current folder: /Users/esmith/Developer/Brett_training_repo
files in this folder:
  __pycache__
  player.py
  python_basics.ipynb
  python_from_wolfram.vsnb
  requirements.txt
  sample_nba_stats.csv
player.py exists: True
player.py size (bytes): 1233

### `numpy` — arrays and numeric math

A NumPy **array** is like a list, but every element is the same type and math is vectorized: you operate on the whole array at once instead of writing a `for` loop.

In [9]:
import numpy as np

game_points = np.array([22, 31, 18, 27, 14, 29, 33])

print("array:", game_points)
print("mean:", game_points.mean())
print("max:", game_points.max())
print("min:", game_points.min())
print("plus 2 (every game):", game_points + 2)
print("shooting a 3-game rolling-style slice [1:4]:", game_points[1:4])

# A 2-D array: 3 players x 4 games
box = np.array(
    [
        [22, 31, 18, 27],
        [14, 29, 33, 21],
        [19, 16, 25, 30],
    ]
)
print("shape (rows, cols):", box.shape)
print("per-player totals:", box.sum(axis=1))
print("per-game totals:", box.sum(axis=0))

array: [22 31 18 27 14 29 33]
mean: 24.857142857142858
max: 33
min: 14
plus 2 (every game): [24 33 20 29 16 31 35]
shooting a 3-game rolling-style slice [1:4]: [31 18 27]
shape (rows, cols): (3, 4)
per-player totals: [98 97 90]
per-game totals: [55 76 76 78]

### `pandas` — tables of data

A pandas **DataFrame** is a labeled table. You will use it for almost any sports (or business) dataset.

In [10]:
import pandas as pd

df = pd.read_csv("sample_nba_stats.csv")
df

            player       team  games  points  rebounds  assists
0     LeBron James     Lakers     71    1766       518      589
1    Stephen Curry   Warriors     74    1954       330      444
2     Nikola Jokic    Nuggets     79    2094       961      711
3     Jayson Tatum    Celtics     74    1983       622      361
4      Luka Doncic  Mavericks     70    2370       644      686
5      A'ja Wilson       Aces     38    1015       445       90
6  Sabrina Ionescu    Liberty     38     710       185      228

In [11]:
# Add a computed column, then sort.
df["ppg"] = df["points"] / df["games"]
df.sort_values("ppg", ascending=False)[["player", "team", "games", "points", "ppg"]]

            player       team  games  points        ppg
4      Luka Doncic  Mavericks     70    2370  33.857143
3     Jayson Tatum    Celtics     74    1983  26.797297
5      A'ja Wilson       Aces     38    1015  26.710526
2     Nikola Jokic    Nuggets     79    2094  26.506329
1    Stephen Curry   Warriors     74    1954  26.405405
0     LeBron James     Lakers     71    1766  24.873239
6  Sabrina Ionescu    Liberty     38     710  18.684211

In [12]:
# Filter rows and summarize by team.
high_usage = df[df["points"] >= 1000]
print("players with 1000+ points:")
print(high_usage[["player", "points"]])

print("\npoints by team:")
print(df.groupby("team")["points"].sum().sort_values(ascending=False))

players with 1000+ points:
          player  points
0   LeBron James    1766
1  Stephen Curry    1954
2   Nikola Jokic    2094
3   Jayson Tatum    1983
4    Luka Doncic    2370
5    A'ja Wilson    1015

points by team:
team
Mavericks    2370
Nuggets      2094
Celtics      1983
Warriors     1954
Lakers       1766
Aces         1015
Liberty       710
Name: points, dtype: int64

## 4. Interoperability with Wolfram Language

Python and Wolfram Language can call each other. That is useful when you want Python's data libraries *and* Wolfram's math, entities, and notebooks.

There are two directions:

| Direction | Where you write it | Tool |
| --- | --- | --- |
| **Wolfram runs inside Python** | this notebook | `wolframclient` |
| **Python runs inside Wolfram** | `python_from_wolfram.vsnb` | `ExternalEvaluate` |

Open **`python_from_wolfram.vsnb`** for the second direction (section 4b).

### 4a. Run Wolfram Language from Python

The [Wolfram Client Library](https://reference.wolfram.com/language/WolframClientForPython/) starts a local Wolfram kernel and evaluates expressions.

You need Wolfram Engine or Mathematica installed. The next cell tries the usual macOS kernel paths, then falls back to auto-discovery. If it still cannot start a kernel, it prints a short note instead of crashing the rest of the notebook.

In [13]:
from wolframclient.evaluation import WolframLanguageSession
from wolframclient.language import wl, wlexpr

# wolframclient looks for a kernel on the PATH. On macOS it is often
# easier to pass the path explicitly. Add your own path if needed.
kernel_candidates = [
    "/Applications/Wolfram.app/Contents/MacOS/WolframKernel",
    "/Applications/Wolfram Engine.app/Contents/MacOS/WolframKernel",
    "/Applications/Mathematica.app/Contents/MacOS/WolframKernel",
    None,  # last resort: auto-discover
]

session = None
last_error = None
for kernel in kernel_candidates:
    try:
        session = WolframLanguageSession(kernel) if kernel else WolframLanguageSession()
        session.start()
        break
    except Exception as exc:
        last_error = exc
        session = None

if session is None:
    print("Could not start a Wolfram kernel from Python.")
    print("Install Wolfram Engine (or Mathematica) and try again.")
    print("Details:", type(last_error).__name__, last_error)
else:
    try:
        # Evaluate a Wolfram Language string.
        squares = session.evaluate(wlexpr("Map[#^2 &, Range[5]]"))
        print("squares of 1..5:", squares)

        # Call a Wolfram function as if it were Python: wl.FunctionName(...)
        pi_approx = session.evaluate(wl.N(wl.Pi, 20))
        print("Pi to 20 digits:", pi_approx)

        stats = session.evaluate(wl.Mean([22, 31, 18, 27, 14]))
        print("Wolfram Mean of scores:", stats)
    finally:
        session.terminate()
        print("Wolfram session closed.")

squares of 1..5: (1, 4, 9, 16, 25)
Pi to 20 digits: 3.14159265358979323846264338327950288582
Wolfram Mean of scores: Rational[112, 5]
Wolfram session closed.

### 4b. The other direction lives in a Wolfram notebook

Python-from-Wolfram is written in Wolfram Language, so it belongs in a `.vsnb` (VS Code / Cursor Wolfram notebook), not here.

Open **`python_from_wolfram.vsnb`** in this folder and evaluate the cells with the Wolfram kernel. You will see `ExternalEvaluate["Python", ...]` run Python and return the result to Wolfram.

## 5. Python for sports statistics

Python is the default toolkit for sports analytics because the whole pipeline lives in one language. You pull a season's box scores from a public API or a downloadable CSV, land them in a pandas DataFrame, then slice, group, and model. The same session can plot a shooting chart, fit a simple expected-points model, or feed a machine-learning library. Analysts at teams, sportsbooks, and sites like FiveThirtyEight and Basketball-Reference-style blogs all work this way: get the data, tidy it, then ask questions the box score does not answer on its own — true shooting percentage, plus-minus, pace, strength of schedule.

You do not need a paid feed to start. Packages such as `nba_api` wrap NBA.com endpoints; college and soccer communities maintain similar clients; many leagues publish CSVs. Once the table is in pandas, the analysis is ordinary data work: `groupby` for team totals, new columns for rates (points per game, assist-to-turnover), filters for home vs away, and `numpy` for the numeric guts. The cells below stay offline on purpose — they use `sample_nba_stats.csv` in this folder — but the pattern is the same if you later replace the CSV with a live API call.

**A typical next step** would look like `from nba_api.stats.endpoints import playergamelog` (or an equivalent for your sport), convert the result with `.get_data_frames()[0]`, then compute the same PPG / RPG / APG columns you see below.

In [14]:
import pandas as pd
from player import Player

stats = pd.read_csv("sample_nba_stats.csv")

# Rate stats: totals become per-game numbers.
stats["ppg"] = stats["points"] / stats["games"]
stats["rpg"] = stats["rebounds"] / stats["games"]
stats["apg"] = stats["assists"] / stats["games"]

print("Scoring leaders (PPG)")
print(stats.sort_values("ppg", ascending=False)[["player", "team", "ppg", "rpg", "apg"]].round(1))
print()
print("Team scoring (total points)")
print(stats.groupby("team")["points"].sum().sort_values(ascending=False))

Scoring leaders (PPG)
            player       team   ppg   rpg  apg
4      Luka Doncic  Mavericks  33.9   9.2  9.8
3     Jayson Tatum    Celtics  26.8   8.4  4.9
5      A'ja Wilson       Aces  26.7  11.7  2.4
2     Nikola Jokic    Nuggets  26.5  12.2  9.0
1    Stephen Curry   Warriors  26.4   4.5  6.0
0     LeBron James     Lakers  24.9   7.3  8.3
6  Sabrina Ionescu    Liberty  18.7   4.9  6.0

Team scoring (total points)
team
Mavericks    2370
Nuggets      2094
Celtics      1983
Warriors     1954
Lakers       1766
Aces         1015
Liberty       710
Name: points, dtype: int64

In [15]:
# Same data, now as Player objects from player.py.
# This is how OOP and pandas meet: the table is for analysis,
# the class is for modeling one athlete at a time.
roster = [
    Player(row.player, row.team, row.points, row.games)
    for row in stats.itertuples()
]

for athlete in roster:
    print(athlete.summary())

best = max(roster, key=lambda p: p.points_per_game())
print()
print("Best PPG on this sheet:", best.name, round(best.points_per_game(), 1))

LeBron James (Lakers) scored 1766 points in 71 games (24.9 PPG).
Stephen Curry (Warriors) scored 1954 points in 74 games (26.4 PPG).
Nikola Jokic (Nuggets) scored 2094 points in 79 games (26.5 PPG).
Jayson Tatum (Celtics) scored 1983 points in 74 games (26.8 PPG).
Luka Doncic (Mavericks) scored 2370 points in 70 games (33.9 PPG).
A'ja Wilson (Aces) scored 1015 points in 38 games (26.7 PPG).
Sabrina Ionescu (Liberty) scored 710 points in 38 games (18.7 PPG).

Best PPG on this sheet: Luka Doncic 33.9

## What to try next

- Change numbers in `player.py`, save, then re-run the import cell (you may need to restart the kernel if Python cached the old class).
- Add a method like `triple_double_threat()` or a property like `league`.
- Add a row to `sample_nba_stats.csv` and re-run the pandas cells.
- Open `python_from_wolfram.vsnb` and run Python from Wolfram.

If imports fail, in a terminal from this folder:

```bash
source .venv/bin/activate
pip install -r requirements.txt
```

Then pick the `.venv` kernel in this notebook.